version: 2

jobs:
  build:
    filter:
      branches:
        only:
          - master
        ignore:
          - circleci_share_images
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/gnarus-api-assets

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ab:a2:d3:ba:38:82:81:23:8f:a6:83:dd:c1:9d:a9:6c"
      - restore_cache:
          keys:
          - node-v1-{{ checksum "package.json" }}

          - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
          - node_modules

      - run:
          name: Executa o script e commita
          only:
             - master
          command: |
              cd bin
              sleep 3m
              ./circleci-commit.sh
